apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-bus
  template:
    metadata:
      labels:
        app: frontend-bus
    spec:
      containers:
        - name: frontend-bus
          image: brahimbtf/frontend-bus:1.0
          ports:
            - containerPort: 5173
