apiVersion: v1
kind: ConfigMap
metadata:
  name: exp-service-config
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expeditionDB
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:  http://eureka-server:8761/eureka/
  EUREKA_INSTANCE_HOSTNAME: expedition-service
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
